# Generated by Django 5.2.3 on 2025-06-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pervious_work', models.CharField(max_length=2000)),
                ('school', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('skills', models.TextField(max_length=2000)),
                ('summary', models.TextField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=2000)),
            ],
        ),
    ]
