# Generated by Django 5.2.3 on 2025-06-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pervious_work',
            new_name='previous_work',
        ),
    ]
